const SERVER_URL ='http://localhost:8002/'
const BASE_URL='https://api.wfgateway.com'
const TOKEN_USER='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTUxNzk0MDYsImp0aSI6IntcImlkXCI6XCJVU1ItMjMwODIzMTQxOTMwXCIsXCJ1c2VybmFtZVwiOlwibG9nZXNod2FyYW5AbWFubml0LmNvXCIsXCJmdWxsbmFtZVwiOlwibG9nZXNod2FyYW5cIixcInJvbGVcIjpcImV4dGVybmFsLXVzZXJcIixcImNvbXBhbnlcIjpcIm1hbm5pdFwiLFwiaXNfYmFja29mZmljZVwiOmZhbHNlLFwic3Vic2NyaWJlZF9zZXJ2aWNlc1wiOltcIndoYXRzYXBwXCJdfSJ9.YKo1hVwoCO7n3X-sDYwkz85meAQ34qhIuaL9r-ijqLo'
export { SERVER_URL ,BASE_URL,TOKEN_USER};
